# -*- coding: utf-8 -*-
"""data_categorization-and-visualization_exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z9qWQeI1tPsLyDO6PRg7-uoaiEgdm0Z_

#Import
"""

import pandas as pd

# products_cl.csv - list of all products in catalogue
url = "https://drive.google.com/file/d/1s7Lai4NSlsYjGEPg1QSOUJobNYVsZBOJ/view?usp=sharing"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
products_cl = pd.read_csv(path)

# brands.csv - separate list of brands in catalogue
url = "https://drive.google.com/file/d/1gEMqSZqCFcRYJySUUbA2Eh6uwba1h9P1/view?usp=sharing"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
brands = pd.read_csv(path)

"""#Using category-IDs to create human-readable categories

##Data Exploration
"""

#looking for most important categories
category_type_df = products_cl.copy()

category_type_df.groupby("type").count().nlargest(50, "sku")

#testbed. scanning items for fitting names
category_type_df.loc[category_type_df["type"] == "10142"].sample(10)

#How many categories should we create?
n = 40
print(f"With the {n} largest types, we account for {((category_type_df.groupby('type').count().nlargest(n, 'sku')['sku'].sum()) / (category_type_df.shape[0]) * 100).round(2)}% of all products.")

#lets to this for maybe 20 or 30
#everything thats left = other
#also, add in brands from different table

category_type_df["short"] = category_type_df["sku"].str[:3]
category_type_df = category_type_df.merge(brands, on="short", how="left").copy()
category_type_df = category_type_df.rename(columns={"long": "brand"}).copy()
category_type_df = category_type_df.drop(columns=["short"]).copy()

category_type_df

"""##Create categories"""

category_type_df["category"] = ""

category_type_df.loc[category_type_df["type"] == "11865403", "category"] += "iPhone and iPad Accessories"
category_type_df.loc[category_type_df["type"] == "12175397", "category"] += "Servers"
category_type_df.loc[category_type_df["type"] == "1298", "category"] += "Already Opened Products"
category_type_df.loc[category_type_df["type"] == "11935397", "category"] += "Storage Devices"
category_type_df.loc[category_type_df["type"] == "11905404", "category"] += "Smart Tech & Connected Gadgets"
category_type_df.loc[category_type_df["type"] == "1282", "category"] += "iMac Computers"
category_type_df.loc[category_type_df["type"] == "12635403", "category"] += "iPhone and iPad Accessories"
category_type_df.loc[category_type_df["type"] == "13835403", "category"] += "MacBook and iMac Accessories"
category_type_df.loc[category_type_df["type"] == "5,74E+15", "category"] += "iMac Computers"
category_type_df.loc[category_type_df["type"] == "1364", "category"] += "Storage Devices"
category_type_df.loc[category_type_df["type"] == "12585395", "category"] += "Adapters and Cables"
category_type_df.loc[category_type_df["type"] == "1296", "category"] += "Monitors"
category_type_df.loc[category_type_df["type"] == "1325", "category"] += "Adapters and Cables"
category_type_df.loc[category_type_df["type"] == "5384", "category"] += "Headphones, Speakers and Bluetooth Devices"
category_type_df.loc[category_type_df["type"] == "1433", "category"] += "Storage Devices"
category_type_df.loc[category_type_df["type"] == "24895185", "category"] += "Apple Watches"
category_type_df.loc[category_type_df["type"] == "24885185", "category"] += "Apple Watches"
category_type_df.loc[category_type_df["type"] == "1216", "category"] += "iPhone and iPad Accessories"
category_type_df.loc[category_type_df["type"] == "118692158", "category"] += "iMac Computers"
category_type_df.loc[category_type_df["type"] == "1230", "category"] += "Adapters and Cables"
category_type_df.loc[category_type_df["type"] == "9094", "category"] += "Smart Tech & Connected Gadgets"
category_type_df.loc[category_type_df["type"] == "8696", "category"] += "MacBook and iMac Accessories"
category_type_df.loc[category_type_df["type"] == "11821715", "category"] += "iPods"
category_type_df.loc[category_type_df["type"] == "1392", "category"] += "Backpacks and Bags"
category_type_df.loc[category_type_df["type"] == "21485407", "category"] += "Tools and Replacement Parts"
category_type_df.loc[category_type_df["type"] == "1387", "category"] += "Keyboards and Computer Mice"
category_type_df.loc[category_type_df["type"] == "113281716", "category"] += "iPhones"
category_type_df.loc[category_type_df["type"] == "5,39E+11", "category"] += "MacBooks"
category_type_df.loc[category_type_df["type"] == "5,49E+11", "category"] += "iPhone and iPad Accessories"
category_type_df.loc[category_type_df["type"] == "42945397", "category"] += "Storage Devices"
category_type_df.loc[category_type_df["type"] == "12645406", "category"] += "Tools and Replacement Parts"
category_type_df.loc[category_type_df["type"] == "2,16E+11", "category"] += "iMac Computers"
category_type_df.loc[category_type_df["type"] == "85651716", "category"] += "iPhones"
category_type_df.loc[category_type_df["type"] == "51601716", "category"] += "iPhones"
category_type_df.loc[category_type_df["type"] == "24215399", "category"] += "Apple Watch Accessories"
category_type_df.loc[category_type_df["type"] == "14305406", "category"] += "Tools and Replacement Parts"
category_type_df.loc[category_type_df["type"] == "5405", "category"] += "iPhone and iPad Accessories"
category_type_df.loc[category_type_df["type"] == "13005399", "category"] += "Power Banks, Docking Stations and Charging Devices"
category_type_df.loc[category_type_df["type"] == "21632158", "category"] += "iMac Computers"
category_type_df.loc[category_type_df["type"] == "2,17E+11", "category"] += "MacBooks"
category_type_df.loc[category_type_df["type"] == "13855401", "category"] += "Keyboards and Computer Mice"
category_type_df.loc[category_type_df["type"] == "12141714", "category"] += "iPads"
category_type_df.loc[category_type_df["type"] == "85641716", "category"] += "iPhones"
category_type_df.loc[category_type_df["type"] == "10230", "category"] += "MacBook and iMac Accessories"
category_type_df.loc[category_type_df["type"] == "10142", "category"] += "Tools and Replacement Parts"
category_type_df.loc[category_type_df["type"] == "1716", "category"] += "iPhones"
category_type_df.loc[category_type_df["type"] == "1416", "category"] += "Software"
category_type_df.loc[category_type_df["type"] == "2434", "category"] += "Apple Watch Accessories"
category_type_df.loc[category_type_df["type"] == "51861714", "category"] += "iPads"
category_type_df.loc[category_type_df["type"] == "1714", "category"] += "iPads"
category_type_df.loc[category_type_df["type"] == "106431714", "category"] += "iPads"
category_type_df.loc[category_type_df["type"] == "51871714", "category"] += "iPads"
category_type_df.loc[category_type_df["type"] == "24811716", "category"] += "iPhones"
category_type_df.loc[category_type_df["type"] == "1276", "category"] += "MacBook and iMac Accessories"
category_type_df.loc[category_type_df["type"] == "13621714", "category"] += "iPads"
category_type_df.loc[category_type_df["type"] == "24821716", "category"] += "iPhones"
category_type_df.loc[category_type_df["type"] == "14365395", "category"] += "Adapters and Cables"
category_type_df.loc[category_type_df["type"] == "14035403", "category"] += "iPhone and iPad Accessories"
category_type_df.loc[category_type_df["type"] == "12575403", "category"] += "iPhone and iPad Accessories"

category_type_df.loc[category_type_df["type"] == "12215397","category"] += 'Storage Devices'
category_type_df.loc[category_type_df["type"] == "5398","category"] += 'Headphones, Speakers and Bluetooth Devices'
category_type_df.loc[category_type_df["type"] == "1,02E+12","category"] += 'MacBooks'
category_type_df.loc[category_type_df["type"] == "1,44E+11","category"] += 'Apple Device Repair Services'
category_type_df.loc[category_type_df["type"] == "57445397","category"] += 'Storage Devices'
category_type_df.loc[category_type_df["type"] == "1334","category"] += 'Network and Connectivity Devices'
category_type_df.loc[category_type_df["type"] == "2158","category"] += 'MacBooks'
category_type_df.loc[category_type_df["type"] == "2449","category"] += 'Apple Watch Accessories'
category_type_df.loc[category_type_df["type"] == "12655397","category"] += 'Storage Devices'
category_type_df.loc[category_type_df["type"] == "1229","category"] += 'iPhone and iPad Accessories'
category_type_df.loc[category_type_df["type"] == "12995397","category"] += 'Power Banks, Docking Stations and Charging Devices'
category_type_df.loc[category_type_df["type"] == "1515","category"] += 'Power Banks, Docking Stations and Charging Devices'
category_type_df.loc[category_type_df["type"] == "13615399","category"] += 'Power Banks, Docking Stations and Charging Devices'
category_type_df.loc[category_type_df["type"] == "13555403","category"] += 'iPhone and iPad Accessories'
category_type_df.loc[category_type_df["type"] == "1405","category"] += 'Tablets and Smart Pads'


category_type_df.loc[category_type_df["category"] == "", "category"] += "Other"

"""##Check categories"""

category_type_df["category"].value_counts()

"""#Download Table"""

from google.colab import files
category_type_df.to_csv("products_category.csv", index=False)
files.download("products_category.csv")

"""#Vizalization of discounts and sales"""

import seaborn as sns

#change display settings of notebook for ease if use
pd.set_option('display.max_rows', 1000)
pd.set_option("display.max_colwidth", 100)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

# orderlines_qu.csv - list of ordered products
url = "https://drive.google.com/file/d/1yWO-mQfxQtnSZdCgdNlIEUrZSCW1HN5O/view?usp=sharing"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
orderlines_qu = pd.read_csv(path)

"""##Merge tables to group sales"""

products_category = category_type_df

merged = orderlines_qu.merge(products_category,
                  on='sku', how="left")

"""##Order best selling categories"""

top = merged.groupby('category').agg(total_sold=('product_quantity', 'sum')).reset_index()

top_20 = top.sort_values(by='total_sold', ascending=False).head(20)

"""##Create graphs"""

to_20_plot = sns.catplot(top_20, y='category', x='total_sold',hue='category', kind='bar', palette="mako", height= 8, aspect=2)


to_20_plot.set(title='Best selling Categories')
ax=to_20_plot.ax
ax.set_xlabel("Total Items Sold")
ax.set_ylabel("Category")
to_20_plot.set_xticklabels(rotation=45);

#calculate and display discounts
merged["discount"] = merged["price"]-merged["unit_price"]
merged["discount_percent"] = (merged["price"]-merged["unit_price"])/(merged["price"])*100
merged.sample(3)

#correct datetime
merged["date"] = pd.to_datetime(merged["date"]).copy()

#filter out negative discounts and create mean discounts per category
filterdisc = merged["discount_percent"]> 0
merged = merged.loc[filterdisc].copy()

top_10_cat = merged.groupby('category').agg(total_sold=('product_quantity', 'sum'), mean_discount_perc=("discount_percent","mean"), mean_discount=("discount","mean")).reset_index()
top_10_cat = top_10_cat.sort_values(by='total_sold', ascending=False).head(30)

to_20_cats = sns.catplot(top_10_cat, y='category', x='mean_discount_perc',hue='category', kind='bar', palette="mako", height= 10, aspect=2)


to_20_cats.set(title='Discounts of Best selling Categories')
ax=to_20_cats.ax
ax.set_xlabel("Discount Percentage")
ax.set_ylabel("Category");

"""##Create more complex graph overlaying revenue and discounts"""

import matplotlib.pyplot as plt

merged['diff'] = merged['price'] - merged['unit_price']
merged["pct_diff"] = merged['diff'] / merged['price']
merged['revenue'] = (
    orderlines_qu['product_quantity'] * orderlines_qu['unit_price']
)

top_revenue = (
    merged
    .groupby('category')
    .agg(
        top_revenue=('revenue', 'sum'),
        mean_discount=('pct_diff', 'mean')
    )
    .reset_index()
    .sort_values('top_revenue')
)

fig, ax1 = plt.subplots(figsize=(16, 12))

bar_width = 0.4
x = range(len(top_revenue))

# Revenue bars (blue, left axis)
ax1.bar(
    [i - bar_width / 2 for i in x],
    top_revenue['top_revenue'],
    width=bar_width,
    label='Top Revenue (€)',
    color='steelblue',
    alpha=0.85
)
ax1.set_ylabel('Top Revenue (€)')

# Discount bars (red, right axis)
ax2 = ax1.twinx()
ax2.bar(
    [i + bar_width / 2 for i in x],
    top_revenue['mean_discount'],
    width=bar_width,
    label='Mean Discount (%)',
    color='firebrick',
    alpha=0.85
)
ax2.set_ylabel('Mean Discount (%)')

# X-axis formatting
ax1.set_xticks(x)
ax1.set_xticklabels(top_revenue['category'])

ax1.xaxis.tick_top()
ax1.xaxis.set_label_position('top')
ax1.set_xlabel('Category')
ax1.tick_params(axis='x', rotation=90)

plt.title('Top Revenue by Category vs Mean Discount')

# Merge legends
lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper right')

plt.tight_layout()
plt.savefig(
    "Top_Revenue_by_Category_vs_Mean_Discount_Bars.png",
    dpi=600,
    transparent=True,
)
plt.show()

#shorten category lables
def truncate_label(text, max_len=30):
    if len(text) <= max_len:
        return text

    truncated = text[:max_len].rsplit(' ', 1)[0]
    return truncated + '...'

#make graph more visually pleasing and annotate highest revenue

max_len = 30

top_revenue['category_short'] = top_revenue['category'].apply(
    lambda x: truncate_label(x, max_len=30)
)

top_revenue['revenue_norm'] = (
    top_revenue['top_revenue'] / top_revenue['top_revenue'].max()
)

top_revenue['discount_norm'] = (
    top_revenue['mean_discount'] / top_revenue['mean_discount'].max()
)

max_idx = top_revenue['top_revenue'].idxmax()
max_x = top_revenue.index.get_loc(max_idx)
max_revenue = top_revenue.loc[max_idx, 'top_revenue']
max_revenue_norm = top_revenue.loc[max_idx, 'revenue_norm']

fig, ax = plt.subplots(figsize=(16, 12))

x = range(len(top_revenue))

# Normalized revenue
ax.bar(
    x,
    top_revenue['revenue_norm'],
    width=0.6,
    label='Revenue (normalized)',
    color='teal',
    alpha=0.85
)

# Normalized discount
bars = ax.bar(
    x,
    top_revenue['discount_norm'],
    width=0.35,
    label='Discount (normalized)',
    color='crimson',
    edgecolor='black',
    linewidth=1,
    alpha=0.9
)

# Annotate with real % values
for bar, pct in zip(bars, top_revenue['mean_discount']):
    ax.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height(),
        f'{pct:.1%}',
        ha='center',
        va='bottom',
        fontsize=9
    )

ax.set_ylabel('Normalized values (0–1)')
ax.set_xticks(x)
ax.set_xticklabels(top_revenue['category_short'])

ax.xaxis.tick_top()
ax.xaxis.set_label_position('top')
ax.set_xlabel('')
ax.tick_params(axis='x', rotation=90)


ax.text(
    max_x,
    max_revenue_norm + 0.03,  # small offset above bar
    f'€{max_revenue:,.0f}',
    ha='center',
    va='bottom',
    fontsize=10,
    fontweight='bold',
    color='black'
)

plt.title('Normalized Revenue vs Discount by Category', fontdict = {'fontsize' : 24})
ax.legend(loc='upper left')

plt.tight_layout()
plt.savefig(
    "Top_Revenue_by_Category_vs_Mean_Discount_Bars.png",
    dpi=600,
    transparent=True,
)
plt.show()

"""##Create graph to look for influence of sale-timing"""

#total Discount: base price*product_quantity  - actual unit price * product_quantity paid
merged['discount_total'] = (
    (merged['price'] * merged['product_quantity'])
    - (merged['unit_price'] * merged['product_quantity'])

)

#Choose period: weekly
merged['week'] = merged['date'].dt.to_period('W')
merged

weekly_summary = merged.groupby('week').agg({
    'revenue': 'sum',
    'discount_total': 'sum'
}).reset_index()

# Convert month back to timestamp for plotting
weekly_summary['week'] = weekly_summary['week'].dt.to_timestamp()
weekly_summary.head(5)

plt.figure(figsize=(10,6))

plt.plot(weekly_summary['week'], weekly_summary['revenue'], label='Full Price Revenue', color='blue')
plt.plot(weekly_summary['week'], weekly_summary['discount_total'], linestyle='--', label='Discounts Given', color='red')

plt.title('Weekly Revenue vs Discounts')
plt.xlabel('week')
plt.ylabel('€')
plt.legend()
plt.tight_layout()

plt.savefig(
    "time_discounts.png",
    dpi=600,
    transparent=True,
)

plt.show()

"""#Download graphs"""

#download
to_20_plot.savefig("best selling categories.png", format="png", dpi=600, transparent=True)
files.download("best selling categories.png")
files.download("Top_Revenue_by_Category_vs_Mean_Discount_Bars.png")
files.download("time_discounts.png")